[2024-05-07T09:49:27.638+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-07T09:49:27.662+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_table_dump.mysql_table_dump_task manual__2024-05-07T09:49:26.484191+00:00 [queued]>
[2024-05-07T09:49:27.674+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_table_dump.mysql_table_dump_task manual__2024-05-07T09:49:26.484191+00:00 [queued]>
[2024-05-07T09:49:27.675+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-07T09:49:27.697+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): mysql_table_dump_task> on 2024-05-07 09:49:26.484191+00:00
[2024-05-07T09:49:27.705+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=836) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-07T09:49:27.707+0000] {standard_task_runner.py:63} INFO - Started process 837 to run task
[2024-05-07T09:49:27.707+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_table_dump', 'mysql_table_dump_task', 'manual__2024-05-07T09:49:26.484191+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dump_load_dag.py', '--cfg-path', '/tmp/tmpsa374vsu']
[2024-05-07T09:49:27.709+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask mysql_table_dump_task
[2024-05-07T09:49:27.774+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_table_dump.mysql_table_dump_task manual__2024-05-07T09:49:26.484191+00:00 [running]> on host 284b5f341ead
[2024-05-07T09:49:27.872+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_table_dump' AIRFLOW_CTX_TASK_ID='mysql_table_dump_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T09:49:26.484191+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-07T09:49:26.484191+00:00'
[2024-05-07T09:49:27.873+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-07T09:49:27.887+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-07T09:49:27.889+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump -u root -proot -h 127.0.0.1 -P 3306 fc_facts facts > /opt/***/dags/dump_file.sql 2>/opt/***/dags/dump_error.log']
[2024-05-07T09:49:27.897+0000] {subprocess.py:86} INFO - Output:
[2024-05-07T09:49:27.910+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-07T09:49:27.911+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-07T09:49:27.925+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-07T09:49:27.930+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=mysql_table_dump, task_id=mysql_table_dump_task, execution_date=20240507T094926, start_date=20240507T094927, end_date=20240507T094927
[2024-05-07T09:49:27.945+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task mysql_table_dump_task (Bash command failed. The command returned a non-zero exit code 2.; 837)
[2024-05-07T09:49:27.964+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-07T09:49:27.980+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-07T09:49:27.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
