[2024-05-05T01:24:43.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T01:24:43.101+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emaildag.send_email scheduled__2024-05-03T01:30:00+00:00 [queued]>
[2024-05-05T01:24:43.113+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emaildag.send_email scheduled__2024-05-03T01:30:00+00:00 [queued]>
[2024-05-05T01:24:43.114+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-05T01:24:43.127+0000] {taskinstance.py:2327} INFO - Executing <Task(EmailOperator): send_email> on 2024-05-03 01:30:00+00:00
[2024-05-05T01:24:43.133+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-05T01:24:43.134+0000] {standard_task_runner.py:63} INFO - Started process 100 to run task
[2024-05-05T01:24:43.134+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emaildag', 'send_email', 'scheduled__2024-05-03T01:30:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/email_dag.py', '--cfg-path', '/tmp/tmpxzqwouhz']
[2024-05-05T01:24:43.136+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask send_email
[2024-05-05T01:24:43.192+0000] {task_command.py:426} INFO - Running <TaskInstance: emaildag.send_email scheduled__2024-05-03T01:30:00+00:00 [running]> on host 8b32424c38fa
[2024-05-05T01:24:43.300+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ngawanggurung@outlook.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emaildag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T01:30:00+00:00'
[2024-05-05T01:24:43.301+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T01:24:43.326+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-05T01:24:43.327+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-05T01:24:43.328+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-05T01:24:43.329+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T01:24:43.330+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-05-05T01:24:43.339+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=emaildag, task_id=send_email, execution_date=20240503T013000, start_date=20240505T012443, end_date=20240505T012443
[2024-05-05T01:24:43.355+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task send_email ([Errno 111] Connection refused; 100)
[2024-05-05T01:24:43.389+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T01:24:43.417+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T01:24:43.421+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
