[2024-05-09T04:05:10.566+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T04:05:10.599+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_table_dump.mysql_task manual__2024-05-09T04:05:09.380867+00:00 [queued]>
[2024-05-09T04:05:10.609+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_table_dump.mysql_task manual__2024-05-09T04:05:09.380867+00:00 [queued]>
[2024-05-09T04:05:10.610+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-09T04:05:10.625+0000] {taskinstance.py:2327} INFO - Executing <Task(MySqlOperator): mysql_task> on 2024-05-09 04:05:09.380867+00:00
[2024-05-09T04:05:10.630+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_table_dump', 'mysql_task', 'manual__2024-05-09T04:05:09.380867+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dump_load_dag.py', '--cfg-path', '/tmp/tmp1i8bnx8x']
[2024-05-09T04:05:10.633+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask mysql_task
[2024-05-09T04:05:10.633+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T04:05:10.634+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2024-05-09T04:05:10.674+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_table_dump.mysql_task manual__2024-05-09T04:05:09.380867+00:00 [running]> on host 14b399cf47d1
[2024-05-09T04:05:10.760+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_table_dump' AIRFLOW_CTX_TASK_ID='mysql_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T04:05:09.380867+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T04:05:09.380867+00:00'
[2024-05-09T04:05:10.761+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T04:05:10.774+0000] {sql.py:276} INFO - Executing: 
    CREATE TABLE free(
        name varchar(255)
    );
[2024-05-09T04:05:10.782+0000] {base.py:84} INFO - Using connection ID 'MySQLID' for task execution.
[2024-05-09T04:05:10.789+0000] {base.py:84} INFO - Using connection ID 'MySQLID' for task execution.
[2024-05-09T04:05:10.807+0000] {sql.py:457} INFO - Running statement: 
    CREATE TABLE free(
        name varchar(255)
    );, parameters: None
[2024-05-09T04:05:10.809+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T04:05:10.810+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'free' already exists")
[2024-05-09T04:05:10.817+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=mysql_table_dump, task_id=mysql_task, execution_date=20240509T040509, start_date=20240509T040510, end_date=20240509T040510
[2024-05-09T04:05:10.828+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task mysql_task ((1050, "Table 'free' already exists"); 302)
[2024-05-09T04:05:10.848+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T04:05:10.862+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T04:05:10.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
